### PR TITLE
Handle more edge cases

### LINKED ISSUE #2: GitHub doesn't allow an underscore
chrome_2017-09-13_19-52-19

```js
var regex = require("regex-username");
regex().test("hello_world"); // true
```

`\w` is an equivalent to `[a-zA-Z0-9_]`.
`\w` captures `_`, but GitHub doesn't allow it in your username.

### PR DESCRIPTION
**Pull request by dguo**
Fixes #2 and #7.

### CODE REVIEW

**Comment by RedSparr0w** [comment]
Nice, could also simplify it more with:
```regex
/^([a-z\d]+-)*[a-z\d]+$/i
```

**Comment by dguo** [comment]
Good points. I replaced the `0-9`s with `\d` and added the case insensitive flag.

**Comment by tunnckoCore** [comment]
Hey @dguo sorry for the delay, not pretty organized recent months! :laughing: 

Thanks! :rocket:

**Comment by tunnckoCore** [comment]
I'll publish new release soon.

**Pull request merged**
